name: Sierra
main: com.github.polyrocketmatt.sierra.impl.Sierra
version: 0.0.1
api-version: 1.13
description: Next generation terrain generation for Minecraft
author: PolyRocketMatt
website: https://github.com/PolyRocketMatt
